name: youtube_player
description: YouTube Application Player
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  lottie: ^1.2.1
  get: ^4.6.1
  cached_network_image: ^3.2.0
  google_fonts: ^2.3.1
  sqflite: ^2.0.2
  get_storage: ^2.0.3
  youtube_player_flutter: ^8.0.0
  intl: ^0.17.0
  charts_flutter: ^0.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - assets/data/
    - assets/images/

